import { defineStore } from "pinia";

const useStaffStore = defineStore("staffStore", {
  state() {
    return {
      staffList: [
        {
          name: "James Rodriguez",
          role: "Head Tennis Coach",
          level: "Senior Level",
          department: "Tennis Academy",
          email: "james.rodriguez@magix.com",
          phoneNumber: "+1 (555) 123-4567",
          date: "15/03/2023",
          status: "Active",
          color: "bg-green-500",
        },
        {
          name: "Sarah Mitchell",
          role: "Swimming Instructor",
          level: "Intermediate Level",
          department: "Swimming Pool",
          email: "sarah.mitchell@magix.com",
          phoneNumber: "+1 (555) 234-5678",
          date: "10/01/2024",
          status: "Active",
          color: "bg-purple-500",
        },
        {
          name: "Michael Chen",
          role: "Fitness Trainer",
          level: "Senior Level",
          department: "Fitness Center",
          email: "michael.chen@magix.com",
          phoneNumber: "+1 (555) 345-6789",
          date: "14/08/2024",
          status: "On Leave",
          color: "bg-green-600",
        },
        {
          name: "Emily Watson",
          role: "Administrative Assistant",
          level: "Junior Level",
          department: "Administration",
          email: "emily.watson@magix.com",
          phoneNumber: "+1 (555) 456-7890",
          date: "13/11/2023",
          status: "Active",
          color: "bg-pink-500",
        },
        {
          name: "David Thompson",
          role: "Maintenance Supervisor",
          level: "Senior Level",
          department: "Maintenance",
          email: "david.thompson@magix.com",
          phoneNumber: "+1 (555) 567-8901",
          date: "07/02/2024",
          status: "Active",
          color: "bg-blue-500",
        },
        {
          name: "Amanda Lee",
          role: "Yoga Instructor",
          level: "Intermediate Level",
          department: "Fitness Center",
          email: "amanda.lee@magix.com",
          phoneNumber: "+1 (555) 678-9012",
          date: "25/12/2023",
          status: "On Leave",
          color: "bg-yellow-500",
        },
        {
          name: "Robert Davis",
          role: "Soccer Coach",
          level: "Senior Level",
          department: "Sports Academy",
          email: "robert.davis@magix.com",
          phoneNumber: "+1 (555) 789-0123",
          date: "18/04/2023",
          status: "Active",
          color: "bg-indigo-500",
        },
        {
          name: "Jessica Taylor",
          role: "Nutrition Specialist",
          level: "Senior Level",
          department: "Wellness Center",
          email: "jessica.taylor@magix.com",
          phoneNumber: "+1 (555) 890-1234",
          date: "22/06/2023",
          status: "Inactive",
          color: "bg-red-500",
        },
        {
          name: "Daniel Wilson",
          role: "Basketball Coach",
          level: "Intermediate Level",
          department: "Sports Academy",
          email: "daniel.wilson@magix.com",
          phoneNumber: "+1 (555) 901-2345",
          date: "05/05/2024",
          status: "Active",
          color: "bg-green-400",
        },
        {
          name: "Sophia Martinez",
          role: "Customer Service Officer",
          level: "Junior Level",
          department: "Front Desk",
          email: "sophia.martinez@magix.com",
          phoneNumber: "+1 (555) 012-3456",
          date: "17/09/2023",
          status: "Active",
          color: "bg-teal-500",
        },
        {
          name: "William Brown",
          role: "IT Support Specialist",
          level: "Senior Level",
          department: "IT Department",
          email: "william.brown@magix.com",
          phoneNumber: "+1 (555) 123-6789",
          date: "30/07/2024",
          status: "On Leave",
          color: "bg-cyan-500",
        },
        {
          name: "Olivia Harris",
          role: "Dance Instructor",
          level: "Intermediate Level",
          department: "Arts & Culture",
          email: "olivia.harris@magix.com",
          phoneNumber: "+1 (555) 234-7890",
          date: "09/12/2023",
          status: "Active",
          color: "bg-pink-400",
        },
        {
          name: "Ethan Walker",
          role: "Lifeguard",
          level: "Junior Level",
          department: "Swimming Pool",
          email: "ethan.walker@magix.com",
          phoneNumber: "+1 (555) 345-8901",
          date: "02/02/2024",
          status: "Inactive",
          color: "bg-gray-500",
        },
        {
          name: "Isabella Lopez",
          role: "Receptionist",
          level: "Junior Level",
          department: "Front Desk",
          email: "isabella.lopez@magix.com",
          phoneNumber: "+1 (555) 456-9012",
          date: "20/08/2023",
          status: "Active",
          color: "bg-orange-500",
        },
        {
          name: "Christopher Young",
          role: "Boxing Trainer",
          level: "Senior Level",
          department: "Fitness Center",
          email: "chris.young@magix.com",
          phoneNumber: "+1 (555) 567-0123",
          date: "12/03/2024",
          status: "Active",
          color: "bg-red-400",
        },
        {
          name: "Mia Scott",
          role: "Kids Activity Coordinator",
          level: "Intermediate Level",
          department: "Kids Club",
          email: "mia.scott@magix.com",
          phoneNumber: "+1 (555) 678-1234",
          date: "06/01/2024",
          status: "On Leave",
          color: "bg-yellow-400",
        },
        {
          name: "Benjamin Allen",
          role: "Security Officer",
          level: "Senior Level",
          department: "Security",
          email: "benjamin.allen@magix.com",
          phoneNumber: "+1 (555) 789-2345",
          date: "28/04/2023",
          status: "Active",
          color: "bg-gray-600",
        },
        {
          name: "Charlotte King",
          role: "Spa Therapist",
          level: "Intermediate Level",
          department: "Spa & Wellness",
          email: "charlotte.king@magix.com",
          phoneNumber: "+1 (555) 890-3456",
          date: "16/07/2024",
          status: "Inactive",
          color: "bg-purple-400",
        },
        {
          name: "Henry Evans",
          role: "Golf Instructor",
          level: "Senior Level",
          department: "Sports Academy",
          email: "henry.evans@magix.com",
          phoneNumber: "+1 (555) 901-4567",
          date: "11/05/2023",
          status: "Active",
          color: "bg-green-700",
        },
        {
          name: "Amelia Baker",
          role: "Event Coordinator",
          level: "Intermediate Level",
          department: "Events",
          email: "amelia.baker@magix.com",
          phoneNumber: "+1 (555) 012-5678",
          date: "29/09/2023",
          status: "Active",
          color: "bg-blue-400",
        },
        {
          name: "Jack Rivera",
          role: "Personal Trainer",
          level: "Senior Level",
          department: "Fitness Center",
          email: "jack.rivera@magix.com",
          phoneNumber: "+1 (555) 123-6780",
          date: "04/10/2024",
          status: "Active",
          color: "bg-lime-500",
        },
        {
          name: "Grace Adams",
          role: "HR Coordinator",
          level: "Senior Level",
          department: "Human Resources",
          email: "grace.adams@magix.com",
          phoneNumber: "+1 (555) 234-6781",
          date: "08/02/2023",
          status: "On Leave",
          color: "bg-fuchsia-500",
        },
        {
          name: "Matthew Parker",
          role: "Cafeteria Supervisor",
          level: "Intermediate Level",
          department: "Food Services",
          email: "matthew.parker@magix.com",
          phoneNumber: "+1 (555) 345-6782",
          date: "21/11/2023",
          status: "Active",
          color: "bg-amber-500",
        },
        {
          name: "Chloe Rivera",
          role: "Music Teacher",
          level: "Junior Level",
          department: "Arts & Culture",
          email: "chloe.rivera@magix.com",
          phoneNumber: "+1 (555) 456-6783",
          date: "12/12/2023",
          status: "Inactive",
          color: "bg-rose-500",
        },
      ],
    };
  },
  getters: {
    loadStaff() {
      return this.staffList;
    },
  },
});

export default useStaffStore;
